version: '3.7'
services:

  app:
    build: .
    image: app-cadastro-produtos
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_NAME="App cadastro de produtos"
      - APP_ENV=local
      - APP_KEY=base64:9bTo6DIHSyY6H44Ysfb3XckGMNwLxEH7kUBlJKlpUEQ=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=loja
      - DB_USERNAME=lojacadastro
      - DB_PASSWORD=12345678
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: loja
      MYSQL_USER: lojacadastro
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver:
      local
