version: '3.7'
services:

  app:
    build: .
    image: app-cadastro-produtos
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: loja
      MYSQL_USER: lojacadastro
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver:
      local
